version: "3.4"

services:

  ath.grpc:
    image: ${DOCKER_REGISTRY-digitalbank}/athgrpc
    build:
      context: .
      dockerfile: src/Services/Ath/Ath.Grpc/Dockerfile

  customer.grpc:
    image: ${DOCKER_REGISTRY-digitalbank}/customergrpc
    build:
      context: .
      dockerfile: src/Services/Customer/Customer.Grpc/Dockerfile


  inperson.grpc:
    image: ${DOCKER_REGISTRY-digitalbank}/inpersongrpc
    build:
      context: .
      dockerfile: src/Services/InPerson/InPerson.Grpc/Dockerfile
