// <auto-generated />
using System;
using InPerson.Grpc.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InPerson.Grpc.Infrastructure.Migrations
{
    [DbContext(typeof(InPersonContext))]
    partial class InPersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("InPerson.Grpc.Model.BankProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountReference")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdClient")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OpeningDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankProduct");
                });

            modelBuilder.Entity("InPerson.Grpc.Model.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardReference")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditCardType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OpeningDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditCard");
                });
#pragma warning restore 612, 618
        }
    }
}
